sudo: required

arch:
  packages:
    # pacman packages
    - python
    - perl
    # aur packages
    - go-git
    # packages from papyros repo
    - papyros-shell
  script:
    - "./build.sh"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
