var MODULESETS = {}; var ROW_KEYS = {}; var ROW_KEY_SIGNATURES = {};
MODULESETS['background_script.js'] = 'background'; ROW_KEYS['background'] = 'classroom-live.background.en_US.OIEjmOmUIs0.OL';
MODULESETS['inject_script.js'] = 'inject'; ROW_KEYS['inject'] = 'classroom-live.inject.en_US.AJyoMto2LFE.OL';
MODULESETS['options_script.js'] = 'options'; ROW_KEYS['options'] = 'classroom-live.options.en_US.zfpN4rCrqLw.OL';
MODULESETS['popup_script.js'] = 'popup'; ROW_KEYS['popup'] = 'classroom-live.popup.en_US.KQjS3PIdG4I.OL';
try{
var h=this,aa="closure_uid_"+(1E9*Math.random()>>>0),ba=Date.now||function(){return+new Date};
}catch(e){_DumpException(e)}
try{
var _DumpException=function(a){throw a;},ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},ea=function(a,b,c){return a.call.apply(a.bind,arguments)},fa=0,ga=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=
Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},l=function(a,b){function c(){}
c.prototype=b.prototype;a.B=b.prototype;a.prototype=new c;a.pa=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}},m=function(a,b,c){m=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:ca;return m.apply(null,arguments)},p=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},q=function(a){return"function"==ga(a)},r=function(a){return"string"==typeof a},ha=function(a){var b= ga(a);return"array"==b||"object"==b&&"number"==typeof a.length},ia=function(a){a.J=void 0;a.G=function(){return a.J?a.J:a.J=new a}},ja=function(){},t=function(a){return void 0!==a};
var ka=function(a,b,c){this.g=c;this.c=a;this.h=b;this.b=0;this.a=null};ka.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.c();return a};var la=function(a,b){a.h(b);a.b<a.g&&(a.b++,b.next=a.a,a.a=b)};var u=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,u);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};l(u,Error);u.prototype.name="CustomError";var ma=function(a,b,c,d,e){this.reset(a,b,c,d,e)};ma.prototype.g=0;ma.prototype.a=null;var na=0;ma.prototype.reset=function(a,b,c,d,e){this.g="number"==typeof e?e:na++;this.j=d||ba();this.b=a;this.h=b;this.c=c;delete this.a};ma.prototype.getMessage=function(){return this.h};
var oa=function(){this.a=ba()};new oa;oa.prototype.set=function(a){this.a=a};oa.prototype.reset=function(){this.set(ba())};oa.prototype.get=function(){return this.a};var v=h.JSON.stringify;var pa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},qa=function(a){var b=0,c;for(c in a)b++;return b},ra=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},sa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},ta=function(a,b){return null!==a&&b in a},ua="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),va=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<ua.length;f++)c= ua[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var xa=function(a,b){var c=wa;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var ya=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Ga=function(a){if(!za.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Aa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ba,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ca,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Da,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ea,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Fa,"&#0;"));return a},Aa=/&/g,Ba=/</g,Ca=/>/g,Da=/"/g,Ea=/'/g,Fa=/\x00/g,za=/[\x00&<>"']/, Ha=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)},Ia=function(a,b){return a<b?-1:a>b?1:0};
var w=function(){this.c=this.c;this.o=this.o};w.prototype.c=!1;w.prototype.b=function(){if(this.o)for(;this.o.length;)this.o.shift()()};var Ja="closure_listenable_"+(1E6*Math.random()|0);var x;a:{var Ka=h.navigator;if(Ka){var La=Ka.userAgent;if(La){x=La;break a}}x=""}var y=function(a){return-1!=x.indexOf(a)};var Ma=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("[goog.string.format] Template required");return d.replace(/%([0\-\ \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,k,G,n,da,Wc){if("%"==n)return"%";var e=c.shift();if("undefined"==typeof e)throw Error("[goog.string.format] Not enough arguments");arguments[0]=e;return z[n].apply(null,arguments)})},z={s:function(a,b,c){return isNaN(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?
a+Ha(" ",Number(c)-a.length):Ha(" ",Number(c)-a.length)+a},f:function(a,b,c,d,e){d=a.toString();isNaN(e)||""==e||(d=parseFloat(a).toFixed(e));var f;f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if(isNaN(c)||d.length>=Number(c))return d;d=isNaN(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+Ha(" ",a):f+Ha(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,g,k){return z.f(parseInt(a, 10),b,c,d,0,f,g,k)}};z.i=z.d;z.u=z.d;
var Na=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(r(a))return r(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},A=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=r(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Oa=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,
b,c)}:function(a,b,c){for(var d=a.length,e=r(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0},Ra=function(a){var b=Pa;a=Qa(b,a,void 0);return 0>a?null:r(b)?b.charAt(a):b[a]},Qa=function(a,b,c){for(var d=a.length,e=r(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1},Sa=function(a,b){0<=Na(a,b)||a.push(b)},Ta=function(a,b){b=Na(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c},Ua=function(a){return Array.prototype.concat.apply(Array.prototype,
arguments)},Va=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Xa=function(a,b,c,d){Array.prototype.splice.apply(a,Wa(arguments,1))},Wa=function(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};
var Ya=function(){this.b=this.a=null},$a=new ka(function(){return new Za},function(a){a.reset()},100);Ya.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var Za=function(){this.next=this.b=this.a=null};Za.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};Za.prototype.reset=function(){this.next=this.b=this.a=null};
var ab=function(a,b){this.type=a;this.a=this.b=b;this.da=!0};var bb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,cb=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e,f=null;0<=d?(e=a[c].substring(0,d),f=a[c].substring(d+1)):e=a[c];b(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}};
var db=function(a,b){ab.call(this,b.request,a);this.message=b};l(db,ab);var eb=function(a){var b=["sender","request","expectResponse"];if(!p(a))return!1;p(b)&&(b=ra(b));return Oa(b,function(b){return ta(a,b)})};var fb=function(a){this.src=a;this.a={};this.b=0};fb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];a:{for(var f=0;f<e.length;++f){var g=e[f];if(!g.removed&&g.listener==b&&g.capture==!!c&&g.ca==d){b=f;break a}}b=-1}return-1<b?(e[b].a(),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1}; fb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,d[e].a();delete this.a[c];this.b--}return b};
var gb=function(a){if(a.w&&"function"==typeof a.w)return a.w();if(r(a))return a.split("");if(ha(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return ra(a)};var hb=function(a){h.setTimeout(function(){throw a;},0)},ib,jb=function(){var a=h.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!y("Presto")&&(a=function(){var a=document.createElement("IFRAME");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,
a=m(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!y("Trident")&&!y("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(t(c.next)){c=c.next;var a=c.P;c.P=null;a()}};return function(a){d.next={P:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("SCRIPT")?function(a){var b= document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){h.setTimeout(a,0)}};
var kb="StopIteration"in h?h.StopIteration:{message:"StopIteration",stack:""},lb=function(){};lb.prototype.next=function(){throw kb;};lb.prototype.h=function(){return this};var mb=y("Opera"),B=y("Trident")||y("MSIE"),nb=y("Edge"),ob=y("Gecko")&&!(-1!=x.toLowerCase().indexOf("webkit")&&!y("Edge"))&&!(y("Trident")||y("MSIE"))&&!y("Edge"),pb=-1!=x.toLowerCase().indexOf("webkit")&&!y("Edge"),qb=function(){var a=h.document;return a?a.documentMode:void 0},rb;
a:{var sb="",tb=function(){var a=x;if(ob)return/rv\:([^\);]+)(\)|;)/.exec(a);if(nb)return/Edge\/([\d\.]+)/.exec(a);if(B)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(pb)return/WebKit\/(\S+)/.exec(a);if(mb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();tb&&(sb=tb?tb[1]:"");if(B){var ub=qb();if(null!=ub&&ub>parseFloat(sb)){rb=String(ub);break a}}rb=sb}
var vb=rb,wa={},C=function(a){return xa(a,function(){for(var b=0,c=ya(String(vb)).split("."),d=ya(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==g[0].length&&0==k[0].length)break;b=Ia(0==g[1].length?0:parseInt(g[1],10),0==k[1].length?0:parseInt(k[1],10))||Ia(0==g[2].length,0==k[2].length)||Ia(g[2],k[2]);g=g[3];k=k[3]}while(0==b)}return 0<=b})},wb;var xb=h.document; wb=xb&&B?qb()||("CSS1Compat"==xb.compatMode?parseInt(vb,10):5):void 0;
var Cb=function(a,b){yb||zb();Ab||(yb(),Ab=!0);var c=Bb,d=$a.get();d.set(a,b);c.b?c.b.next=d:c.a=d;c.b=d},yb,zb=function(){if(-1!=String(h.Promise).indexOf("[native code]")){var a=h.Promise.resolve(void 0);yb=function(){a.then(Db)}}else yb=function(){var a=Db;!q(h.setImmediate)||h.Window&&h.Window.prototype&&!y("Edge")&&h.Window.prototype.setImmediate==h.setImmediate?(ib||(ib=jb()),ib(a)):h.setImmediate(a)}},Ab=!1,Bb=new Ya,Db=function(){for(var a;a=Bb.remove();){try{a.a.call(a.b)}catch(b){hb(b)}la($a, a)}Ab=!1};
var Eb=!B||9<=Number(wb);!ob&&!B||B&&9<=Number(wb)||ob&&C("1.9.1");B&&C("9");B&&C("9");!pb||C("528");ob&&C("1.9b")||B&&C("8")||mb&&C("9.5")||pb&&C("528");ob&&!C("8")||B&&C("9");var D=function(a,b){this.b={};this.a=[];this.g=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof D?(c=a.F(),d=a.w()):(c=sa(a),d=ra(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};D.prototype.w=function(){Fb(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};D.prototype.F=function(){Fb(this);return this.a.concat()};
D.prototype.remove=function(a){return E(this.b,a)?(delete this.b[a],this.c--,this.g++,this.a.length>2*this.c&&Fb(this),!0):!1};var Fb=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];E(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],E(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};D.prototype.get=function(a,b){return E(this.b,a)?this.b[a]:b};
D.prototype.set=function(a,b){E(this.b,a)||(this.c++,this.a.push(a),this.g++);this.b[a]=b};D.prototype.forEach=function(a,b){for(var c=this.F(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};D.prototype.h=function(a){Fb(this);var b=0,c=this.g,d=this,e=new lb;e.next=function(){if(c!=d.g)throw Error("The map has changed since the iterator was created");if(b>=d.a.length)throw kb;var e=d.a[b++];return a?e:d.b[e]};return e}; var E=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var Gb=function(a){var b=document;return r(a)?b.getElementById(a):a},Ib=function(a,b){pa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Hb.hasOwnProperty(d)?a.setAttribute(Hb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},Hb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",
usemap:"useMap",valign:"vAlign",width:"width"},Kb=function(a,b,c){var d=arguments,e=document,f=String(d[0]),g=d[1];if(!Eb&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',Ga(g.name),'"');if(g.type){f.push(' type="',Ga(g.type),'"');var k={};va(k,g);delete k.type;g=k}f.push(">");f=f.join("")}f=e.createElement(f);g&&(r(g)?f.className=g:"array"==ga(g)?f.className=g.join(" "):Ib(f,g));2<d.length&&Jb(e,f,d);return f},Jb=function(a,b,c){function d(c){c&&b.appendChild(r(c)?a.createTextNode(c):c)}
for(var e=2;e<c.length;e++){var f=c[e];!ha(f)||p(f)&&0<f.nodeType?d(f):A(Lb(f)?Va(f):f,d)}},Mb=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)},Lb=function(a){if(a&&"number"==typeof a.length){if(p(a))return"function"==typeof a.item||"string"==typeof a.item;if(q(a))return"function"==typeof a.item}return!1};
var H=function(a,b){this.a=0;this.o=void 0;this.g=this.b=this.c=null;this.h=this.j=!1;this.l=[];Nb(this,Error("created"));this.v=0;if(a!=ja)try{var c=this;a.call(b,function(a){F(c,2,a)},function(a){F(c,3,a)})}catch(d){F(this,3,d)}},Ob=function(){this.next=this.g=this.b=this.h=this.a=null;this.c=!1};Ob.prototype.reset=function(){this.g=this.b=this.h=this.a=null;this.c=!1};var Pb=new ka(function(){return new Ob},function(a){a.reset()},100),Qb=function(a,b,c){var d=Pb.get();d.h=a;d.b=b;d.g=c;return d};
H.prototype.then=function(a,b,c){Nb(this,Error("then"));return Rb(this,q(a)?a:null,q(b)?b:null,c)};H.prototype.then=H.prototype.then;H.prototype.$goog_Thenable=!0;H.prototype.cancel=function(a){0==this.a&&Cb(function(){var b=new Sb(a);Tb(this,b)},this)};
var Tb=function(a,b){if(0==a.a)if(a.c){var c=a.c;if(c.b){for(var d=0,e=null,f=null,g=c.b;g&&(g.c||(d++,g.a==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.a&&1==d?Tb(c,b):(f?(d=f,d.next==c.g&&(c.g=d),d.next=d.next.next):Ub(c),Vb(c,e,3,b)))}a.c=null}else F(a,3,b)},Xb=function(a,b){a.b||2!=a.a&&3!=a.a||Wb(a);a.g?a.g.next=b:a.b=b;a.g=b},Rb=function(a,b,c,d){var e=Qb(null,null,null);e.a=new H(function(a,g){e.h=b?function(c){try{var e=b.call(d,c);a(e)}catch(n){g(n)}}:a;e.b=c?function(b){try{var e=c.call(d,
b);!t(e)&&b instanceof Sb?g(b):a(e)}catch(n){g(n)}}:g});e.a.c=a;Xb(a,e);return e.a};H.prototype.C=function(a){this.a=0;F(this,2,a)};H.prototype.D=function(a){this.a=0;F(this,3,a)};
var F=function(a,b,c){if(0==a.a){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.a=1;var d;a:{var e=c,f=a.C,g=a.D;if(e instanceof H)Nb(e,Error("then")),Xb(e,Qb(f||ja,g||null,a)),d=!0;else{var k;if(e)try{k=!!e.$goog_Thenable}catch(n){k=!1}else k=!1;if(k)e.then(f,g,a),d=!0;else{if(p(e))try{var G=e.then;if(q(G)){Yb(e,G,f,g,a);d=!0;break a}}catch(n){g.call(a,n);d=!0;break a}d=!1}}}d||(a.o=c,a.a=b,a.c=null,Wb(a),3!=b||c instanceof Sb||Zb(a,c))}},Yb=function(a,b,c,d,e){var f=!1,g=function(a){f||
(f=!0,c.call(e,a))},k=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,g,k)}catch(G){k(G)}},Wb=function(a){a.j||(a.j=!0,Cb(a.A,a))},Ub=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.g=null);return b};H.prototype.A=function(){for(var a;a=Ub(this);)this.v++,Vb(this,a,this.a,this.o);this.j=!1};
var Vb=function(a,b,c,d){if(3==c&&b.b&&!b.c)for(;a&&a.h;a=a.c)a.h=!1;if(b.a)b.a.c=null,$b(b,c,d);else try{b.c?b.h.call(b.g):$b(b,c,d)}catch(e){ac.call(null,e)}la(Pb,b)},$b=function(a,b,c){2==b?a.h.call(a.g,c):a.b&&a.b.call(a.g,c)},Nb=function(a,b){if(r(b.stack)){var c=b.stack.split("\n",4)[3];b=b.message;b+=Array(11-b.length).join(" ");a.l.push(b+c)}},Zb=function(a,b){a.h=!0;Cb(function(){if(a.h){if(b&&r(b.stack)&&a.l.length){for(var c=["Promise trace:"],d=a;d;d=d.c){for(var e=a.v;0<=e;e--)c.push(d.l[e]); c.push("Value: ["+(3==d.a?"REJECTED":"FULFILLED")+"] <"+String(d.o)+">")}b.stack+="\n\n"+c.join("\n")}ac.call(null,b)}})},ac=hb,Sb=function(a){u.call(this,a)};l(Sb,u);Sb.prototype.name="cancel";
var I=function(a){this.a=new D;if(a){a=gb(a);for(var b=a.length,c=0;c<b;c++){var d=a[c];this.a.set(bc(d),d)}}},bc=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[aa]||(a[aa]=++fa)):b.substr(0,1)+a};I.prototype.removeAll=function(a){a=gb(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};I.prototype.remove=function(a){return this.a.remove(bc(a))};I.prototype.contains=function(a){a=bc(a);return E(this.a.b,a)};I.prototype.w=function(){return this.a.w()};I.prototype.h=function(){return this.a.h(!1)};
var J=function(a,b){this.b=this.o=this.c="";this.l=null;this.g=this.a="";this.h=!1;var c;a instanceof J?(this.h=t(b)?b:a.h,cc(this,a.c),this.o=a.o,this.b=a.b,dc(this,a.l),this.a=a.a,ec(this,fc(a.j)),this.g=a.g):a&&(c=String(a).match(bb))?(this.h=!!b,cc(this,c[1]||"",!0),this.o=gc(c[2]||""),this.b=gc(c[3]||"",!0),dc(this,c[4]),this.a=gc(c[5]||"",!0),ec(this,c[6]||"",!0),this.g=gc(c[7]||"")):(this.h=!!b,this.j=new K(null,0,this.h))};
J.prototype.toString=function(){var a=[],b=this.c;b&&a.push(hc(b,ic,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.o)&&a.push(hc(b,ic,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.l,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(hc(c,"/"==c.charAt(0)?jc:kc,!0));(c=this.j.toString())&&a.push("?",c);(c=this.g)&&a.push("#",hc(c,lc));return a.join("")};
var cc=function(a,b,c){a.c=c?gc(b,!0):b;a.c&&(a.c=a.c.replace(/:$/,""))},dc=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.l=b}else a.l=null},ec=function(a,b,c){b instanceof K?(a.j=b,mc(a.j,a.h)):(c||(b=hc(b,nc)),a.j=new K(b,0,a.h))},oc=function(a){return a instanceof J?new J(a):new J(a,void 0)},pc=function(){var a=L;if(".."==a||"."==a)return"";if(-1!=a.indexOf("./")||-1!=a.indexOf("/.")){for(var b=0==a.lastIndexOf("/",0),a=a.split("/"),c=[],d=0;d<a.length;){var e=
a[d++];"."==e?b&&d==a.length&&c.push(""):".."==e?((1<c.length||1==c.length&&""!=c[0])&&c.pop(),b&&d==a.length&&c.push("")):(c.push(e),b=!0)}return c.join("/")}return a},gc=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},hc=function(a,b,c){return r(a)?(a=encodeURI(a).replace(b,qc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},qc=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},ic=/[#\/\?@]/g,kc=/[\#\?:]/g,jc=/[\#\?]/g,
nc=/[\#\?@]/g,lc=/#/g,K=function(a,b,c){this.b=this.a=null;this.c=a||null;this.g=!!c},M=function(a){a.a||(a.a=new D,a.b=0,a.c&&cb(a.c,function(b,c){b=decodeURIComponent(b.replace(/\+/g," "));M(a);a.c=null;b=N(a,b);var d=a.a.get(b);d||a.a.set(b,d=[]);d.push(c);a.b+=1}))};K.prototype.remove=function(a){M(this);a=N(this,a);return E(this.a.b,a)?(this.c=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};var rc=function(a,b){M(a);b=N(a,b);return E(a.a.b,b)};
K.prototype.F=function(){M(this);for(var a=this.a.w(),b=this.a.F(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};K.prototype.w=function(a){M(this);var b=[];if(r(a))rc(this,a)&&(b=Ua(b,this.a.get(N(this,a))));else{a=this.a.w();for(var c=0;c<a.length;c++)b=Ua(b,a[c])}return b};K.prototype.set=function(a,b){M(this);this.c=null;a=N(this,a);rc(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};
K.prototype.get=function(a,b){a=a?this.w(a):[];return 0<a.length?String(a[0]):b};K.prototype.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.F(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.w(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}return this.c=a.join("&")};
var fc=function(a){var b=new K;b.c=a.c;a.a&&(b.a=new D(a.a),b.b=a.b);return b},N=function(a,b){b=String(b);a.g&&(b=b.toLowerCase());return b},mc=function(a,b){b&&!a.g&&(M(a),a.c=null,a.a.forEach(function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),this.remove(c),0<a.length&&(this.c=null,this.a.set(N(this,c),Va(a)),this.b+=a.length))},a));a.g=b};
var sc=oc("https://classroomlive-pa.googleapis.com"),O=oc("/v2/"),P=new J(sc),Q=!!O.c;Q?cc(P,O.c):Q=!!O.o;Q?P.o=O.o:Q=!!O.b;Q?P.b=O.b:Q=null!=O.l;var L=O.a;if(Q)dc(P,O.l);else if(Q=!!O.a){if("/"!=L.charAt(0))if(sc.b&&!sc.a)L="/"+L;else{var tc=P.a.lastIndexOf("/");-1!=tc&&(L=P.a.substr(0,tc+1)+L)}L=pc()}Q?P.a=L:Q=""!==O.j.toString();Q?ec(P,fc(O.j)):Q=!!O.g;Q&&(P.g=O.g);
var R=chrome.i18n.getMessage("2050089326602918210");chrome.i18n.getMessage("4849976898594713883",[R,"https://classroomlive-pa.googleapis.com"]);chrome.i18n.getMessage("9217362152767454370",[R]);chrome.i18n.getMessage("7604563725603697690");chrome.i18n.getMessage("533692309512814645");chrome.i18n.getMessage("7826444313570725162");chrome.i18n.getMessage("5936353814217802658");chrome.i18n.getMessage("1258929983314547244");chrome.i18n.getMessage("4491595920888170943");chrome.i18n.getMessage("8657495129257769609");
chrome.i18n.getMessage("9200475522066047621");chrome.i18n.getMessage("6042567254866620046",[R]);chrome.i18n.getMessage("7798244153502527716",[R]);chrome.i18n.getMessage("4811423455816775324",[R]);chrome.i18n.getMessage("3727581148109420602");chrome.i18n.getMessage("826991190228103925");chrome.i18n.getMessage("4748990655911819545");var uc=chrome.i18n.getMessage("7582805180132294390",[R]);chrome.i18n.getMessage("6576961868476783976",[R]);
var vc=function(a){this.h=a;this.a=this.g=this.b=this.c=null},S=function(a,b){this.name=a;this.value=b};S.prototype.toString=function(){return this.name};var wc=new S("WARNING",900),xc=new S("INFO",800),yc=new S("CONFIG",700),zc=new S("FINE",500),Pa=[new S("OFF",Infinity),new S("SHOUT",1200),new S("SEVERE",1E3),wc,xc,yc,zc,new S("FINER",400),new S("FINEST",300),new S("ALL",0)],Ac=function(a,b){a.a||(a.a=[]);a.a.push(b)};vc.prototype.getChildren=function(){this.g||(this.g={});return this.g};
var Bc=function(a,b){a.b=b},Cc=function(a){return a.b?a.b:a.c?Cc(a.c):null};vc.prototype.log=function(a,b,c){if(a.value>=Cc(this).value)for(q(b)&&(b=b()),a=new ma(a,String(b),this.h),c&&(a.a=c),c="log:"+a.getMessage(),h.console&&(h.console.timeStamp?h.console.timeStamp(c):h.console.markTimeline&&h.console.markTimeline(c)),h.msWriteProfilerMark&&h.msWriteProfilerMark(c),c=this;c;){var d=c,e=a;if(d.a)for(var f=0;b=d.a[f];f++)b(e);c=c.c}};
var Dc={},Ec=null,Fc=function(){Ec||(Ec=new vc(""),Dc[""]=Ec,Ec.b=yc)},Gc=function(){Fc();return Ec},Hc=function(a){Fc();var b;if(!(b=Dc[a])){b=new vc(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=Hc(a.substr(0,c));c.getChildren()[d]=b;b.c=c;Dc[a]=b}return b};
var T=function(){w.call(this);this.j=new fb(this);this.R=this;this.D=null};l(T,w);T.prototype[Ja]=!0;T.prototype.b=function(){T.B.b.call(this);this.j&&this.j.removeAll(void 0);this.D=null};
var Ic=function(a,b,c,d){b=a.j.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.removed&&g.capture==c){var k=g.listener,G=g.ca||g.src;if(g.qa){var n=a.j,da=g.type;da in n.a&&Ta(n.a[da],g)&&(g.a(),0==n.a[da].length&&(delete n.a[da],n.b--))}e=!1!==k.call(G,d)&&e}}return e&&0!=d.da};
var Jc=function(a){return v({t:a.j,ln:a.b.name,lv:a.b.value,m:a.getMessage(),n:a.c,s:a.g,e:a.a&&a.a.message})};var U=function(a,b){a&&a.log(wc,b,void 0)},Kc=function(a,b){a&&a.log(zc,b,void 0)};var Mc=function(a,b,c,d){u.call(this,a);this.details=b?r(b)?b:b.message:void 0;this.helpText=c;this.errorType=d;a=h.MODULESETS;qa(a)&&(a=Ma("chrome-extension://%s/(%s):(\\d+):(\\d+)",chrome.runtime.id,sa(a).join("|")),this.stack=this.stack.replace(new RegExp(a,"g"),Lc));a=Hc("edulive.errors.Error");Kc(a,this.toString())};l(Mc,u);Mc.prototype.name="edulive.errors.Error";
var Lc=function(a,b,c,d){var e=h.MODULESETS;b=e[b];if(!b)return a;a=h.ROW_KEYS[b];var f=h.ROW_KEY_SIGNATURES[b];c-=qa(e)+1;return f?Ma("https://www.gstatic.com/classroom-live/_/js/k=%s/m=%s/rt=j/d=1/rs=%s:%d:%d",a,b,f,c,d):Ma("https://www.gstatic.com/classroom-live/_/js/k=%s/m=%s/rt=j/d=1:%d:%d",a,b,c,d)},Oc=function(a){Mc.call(this,"");A(ra(Nc),function(b){b in a&&(this[b]=a[b])},this)};l(Oc,Mc);Oc.prototype.name="edulive.errors.SerializedError"; var Nc={ea:"columnNumber",fa:"details",ga:"errorType",ha:"fileName",ia:"helpText",ja:"lineNumber",ka:"message",la:"name",ma:"stack",na:"status",oa:"type"};
var V=function(a){w.call(this);this.h=(a||5242880)/2;this.v=!1;this.g=[];this.a=0;this.j=m(this.A,this);this.l=new I};l(V,w);ia(V);V.prototype.b=function(){Pc(this,!1);V.B.b.call(this)};var Pc=function(a,b){if(b!=a.v){var c=Gc();if(b)Ac(c,a.j);else{(c=c.a)&&Ta(c,a.j);c=a.g;if("array"!=ga(c))for(var d=c.length-1;0<=d;d--)delete c[d];c.length=0;a.a=0}a.v=b}};
V.prototype.A=function(a){if(!this.l.contains(a.c)&&a){a=Jc(a);var b=a.length;if(!(b>this.h)){var c=b-(this.h-this.a);if(b+this.a>this.h){var d=0,e=Qa(this.g,function(a){d+=a.length;return d>=c},this);Xa(this.g,0,e+1);this.a-=d}Sa(this.g,a);this.a+=b}}};
var Qc=function(a,b){var c=a.getAttribute("data-sender"),d=a.getAttribute("data-request"),e=a.getAttribute("data-params");a=a.getAttribute("data-expectResponse");var f;if(!c)return b&&U(b,"Missing data-sender attribute"),null;if(!d)return b&&U(b,"Missing data-request attribute"),null;if(a)a=a==(!0).toString();else return b&&U(b,"Missing data-response attribute"),null;if(e)try{f=JSON.parse(e)}catch(g){if(g instanceof SyntaxError)return b&&U(b,"Invalid data-params attribute"),null}return{sender:c,request:d, params:f,expectResponse:a}};
var W=function(a,b,c){w.call(this);this.g=a;this.v=b||0;this.h=c;this.j=m(this.l,this)};l(W,w);W.prototype.a=0;W.prototype.b=function(){W.B.b.call(this);this.stop();delete this.g;delete this.h};W.prototype.start=function(a){this.stop();var b=this.j;a=t(a)?a:this.v;if(!q(b))if(b&&"function"==typeof b.handleEvent)b=m(b.handleEvent,b);else throw Error("Invalid listener argument");this.a=2147483647<Number(a)?-1:h.setTimeout(b,a||0)}; W.prototype.stop=function(){0!=this.a&&h.clearTimeout(this.a);this.a=0};W.prototype.l=function(){this.a=0;this.g&&this.g.call(this.h)};
var Rc=function(a,b,c){Mc.call(this,a,b,c,"connection")};l(Rc,Mc);Rc.prototype.name="edulive.messaging.Error";var X=function(a,b){T.call(this);this.a=a;this.id=b||window.location.pathname;this.V=!("undefined"==typeof window.chrome||!chrome||!chrome.runtime)};l(X,T);X.prototype.sendRequest=function(a,b,c){return new H(function(d,e){var f;f={sender:this.id,request:a,params:b,expectResponse:!0};var g=c||4E4,g=new W(m(this.ba,this,d,e,f),g);d=m(this.aa,this,d,e,f,g);Kc(this.a,this.id+": Sending (and expect response):"+v(f));this.sendMessage(f,d);g.start()},this)};
X.prototype.sendMessage=function(a,b){if(!this.V)throw new Rc("Not running in Chrome.",navigator.appVersion);chrome.runtime.sendMessage(a,b)};
X.prototype.aa=function(a,b,c,d,e){var f=chrome.runtime.lastError;d.c||(d.c=!0,d.b());f?(U(this.a,this.id+": Failed sending "+c.request+". Reason: "+f.message),b(new Rc("Failed to dispatch message. There was no recipient to receive the message.",f))):p(e)&&(t(e.response)||t(e.error))?(d=this.a,c=this.id+": Received response: "+v(e)+" for message: "+v(c),d&&d.log(e.error?wc:zc,c,void 0),t(e.response)?a(e.response):b(new Oc(e.error))):b(new Rc("Invalid response from message request.",v(e)))}; X.prototype.ba=function(a,b,c){U(this.a,this.id+": Failed to receive a response to "+c.request+" in the time alotted.");b(new Rc("Failed to receive a response in the time alotted.",c.request,uc))};
var Y=function(a,b){b=b||Hc("edulive.messaging.InternalMessageDispatcher");X.call(this,b,a);this.l=m(this.X,this);chrome.runtime.onMessage.addListener(this.l);chrome.runtime.onMessageExternal&&chrome.runtime.onMessageExternal.addListener(this.l);this.L=m(this.S,this);chrome.runtime.onConnectExternal&&chrome.runtime.onConnectExternal.addListener(this.L);this.I={};this.g={};this.H={}};l(Y,X);ia(Y);
Y.prototype.b=function(){A(sa(this.g),function(a){Sc(this,a,!0)},this);this.I={};chrome.runtime.onConnectExternal&&chrome.runtime.onConnectExternal.removeListener(this.L);chrome.runtime.onMessageExternal&&chrome.runtime.onMessageExternal.removeListener(this.l);chrome.runtime.onMessage.removeListener(this.l);Y.B.b.call(this)};Y.prototype.sendMessage=function(a,b){b&&Tc(this,a,b)||Y.B.sendMessage.call(this,a,b);b||Uc(this,a)};var Uc=function(a,b){pa(a.g,function(a){a.postMessage(b)},a)};
Y.prototype.X=function(a,b,c){if(!t(a)||!p(a))return!1;if(!eb(a))return U(this.a,this.id+": Invalid message: "+v(a)+" from: "+v(b)),!1;Kc(this.a,this.id+": Received message: "+v(a)+" from: "+v(b));if(a.expectResponse)return this.O(b.id,a,c);this.K(a);return!1};
Y.prototype.K=function(a){var b=new db(this,a),c;if(a=this.D)for(c=[];a;a=a.D)c.push(a);a=this.R;var d=b.type||b;if(r(b))b=new ab(b,a);else if(b instanceof ab)b.b=b.b||a;else{var e=b,b=new ab(d,a);va(b,e)}var e=!0,f;if(c)for(var g=c.length-1;0<=g;g--)f=b.a=c[g],e=Ic(f,d,!0,b)&&e;f=b.a=a;e=Ic(f,d,!0,b)&&e;e=Ic(f,d,!1,b)&&e;if(c)for(g=0;g<c.length;g++)f=b.a=c[g],e=Ic(f,d,!1,b)&&e};Y.prototype.O=function(a,b,c){return a==chrome.runtime.id&&b.sender==this.id?!1:Tc(this,b,c)};
var Tc=function(a,b,c){var d=b.request;if(!ta(a.I,d))return!1;var e=new db(a,b);try{var f=(0,a.I[d])(e);if(f){var g=m(a.$,a,b,c),k=m(a.A,a,b,c);f.then(g,k)}return!!f}catch(G){return a.A(b,c,G),!1}};Y.prototype.$=function(a,b,c){try{JSON.stringify(c),Kc(this.a,"Responding to "+v(a)+" with "+v(c)),b({response:c})}catch(d){this.A(a,b,d)}};
Y.prototype.A=function(a,b,c){if("Attempting to use a disconnected port object"==c.message)U(this.a,a.sender+" disconnected! Cannot respond to "+v(a));else{c instanceof Error&&(c=new Oc(c));try{JSON.stringify(c),U(this.a,"Responding to "+v(a)+" with the error "+v(c)),b({error:Object(c)})}catch(d){U(this.a,"Failed to serialize: "+(q(c.toString)?c.toString():c)+". Returning "+(q(d.toString)?d.toString():d)+" instead."),this.A(a,b,d)}}};
var Sc=function(a,b,c){var d=a.a;d&&d.log(xc,"Ending connection with "+b,void 0);if(d=a.g[b]){var e=a.g;b in e&&delete e[b];c&&d.disconnect();c=a.H[b];a=a.H;b in a&&delete a[b];d.onDisconnect.removeListener(c)}};
Y.prototype.S=function(a){if(a.name!=this.id)Kc(this.a,"Ignoring connection from "+JSON.stringify(a)+" because it is for another page.");else{var b=a.sender;if(b){var c=[];b.id&&c.push(b.id);b.url&&c.push(b.url);c.length?(b=c.join("|"),ta(this.g,b)?(U(this.a,"Already have a connection with "+b+". Disconnecting"),a.disconnect()):((c=this.a)&&c.log(xc,"Establishing connection with "+b,void 0),this.g[b]=a,c=m(this.T,this,b),a.onDisconnect.addListener(c),this.H[b]=c)):(U(this.a,"Could not find an id for "+ JSON.stringify(a)+". Disconnecting."),a.disconnect())}}};Y.prototype.T=function(a){Sc(this,a)};
var Z=function(a){this.h=chrome.runtime.id;Y.call(this,a||"messaging:"+this.h,Hc("edulive.messaging.InjectedMessageDispatcher"));this.C=Vc("messaging:"+this.h);this.Z=Vc("requests:"+this.h,this.C);this.U=Vc("events:"+this.h,this.C);this.N=new MutationObserver(m(this.W,this));this.N.observe(this.Z,{childList:!0});this.v={};(a=this.a)&&a.log(xc,"Installed for "+this.h,void 0)};l(Z,Y);ia(Z);Z.prototype.b=function(){this.N.disconnect();pa(this.v,function(a){a.cancel()},this);this.v={};Mb(this.C);Z.B.b.call(this)};
Z.prototype.K=function(a){var b=this.U,c;do c=["message",a.sender,a.request,ba(),Math.floor(1E6*Math.random())].join(":");while(Gb(c));var d={};d["data-sender"]=a.sender;d["data-request"]=a.request;d["data-expectResponse"]=a.expectResponse;t(a.params)&&(d["data-params"]=JSON.stringify(a.params));d.id=c;d.style="display:none";a=Kb("DIV",d);b&&b.appendChild(a)};Z.prototype.O=function(){return!1};
var Vc=function(a,b){var c={};b=b||document.body;c.id=a;c.style="display:none";a=Kb("DIV",c);b.appendChild(a);return a};
Z.prototype.W=function(a){a&&A(a,function(a){a.addedNodes&&A(Va(a.addedNodes),function(a){var b=a.getAttribute("id")||"unknown";if((a=Qc(a,this.a))&&a.expectResponse){var c=m(this.M,this,b,"data-response"),f=m(this.M,this,b,"data-error");a=this.sendRequest(a.request,a.params).then(c,f);c=m(this.Y,this,b);Nb(a,Error("thenAlways"));c=Qb(c,c,void 0);c.c=!0;Xb(a,c);this.v[b]=a}else U(this.a,"Skipping invalid request "+b)},this)},this)}; Z.prototype.M=function(a,b,c){var d=Gb(a);d?d.setAttribute(b,JSON.stringify(c)):U(this.a,a+" was removed before the response was received.")};Z.prototype.Y=function(a){var b=this.v;a in b&&delete b[a]};
(function(a,b){V.G();var c=b||Ra(function(a){return"INFO"==a.name});a=a||!/^[\s\xa0]*$/.test("")&&[""];b="HangingGetChannel LcsPushChannel invalidation-hr goog.net.BrowserChannel webmonitoring.MemoryUsageReporter wiz.Dispatcher goog.net.NetworkTester BrowserChannelImpl bc-watchdog".split(" ");var d=V.G();null!=c&&Bc(Gc(),c);if(a&&0<a.length)for(var c=function(a){d.A(a)},e=0;e<a.length;++e)Ac(Hc(a[e]),c);else Pc(d,!0);b&&0<b.length&&A(b,function(a){d.l.a.set(bc(a),a)})})();Z.G(); document.addEventListener("unload",function(){var a=Z.G();a.c||(a.c=!0,a.b())});

}catch(e){_DumpException(e)}
// Google Inc.
